clear all
% read dataset
imds = imageDatastore('dataset_10000\','IncludeSubfolders',true,'LabelSource','foldernames','FileExtensions',{'.mat'});

% split data to training and testing sets.
[imdsTrain,imdsTest] = splitEachLabel(imds,0.7,'randomized');

% read data into memory
imdsTrain.Labels = categorical(imdsTrain.Labels);
imdsTrain.ReadFcn = @readFcnMatFile;
 
imdsTest.Labels = categorical(imdsTest.Labels);
imdsTest.ReadFcn = @readFcnMatFile;

labelCount = countEachLabel(imds)

% training options configuration
batchSize   = 128;
ValFre      = fix(length(imdsTrain.Files)/batchSize);
options = trainingOptions('sgdm', ...
    'MiniBatchSize',batchSize, ...
    'MaxEpochs',5, ...
    'Shuffle','every-epoch',...
    'InitialLearnRate',0.001, ...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropPeriod',4,...
    'LearnRateDropFactor',0.1,...
    'ValidationData',imdsTest, ...
    'ValidationFrequency',ValFre, ...
    'ValidationPatience',Inf, ...
    'Verbose',true ,...
    'VerboseFrequency',ValFre,...
    'Plots','training-progress',...
    'ExecutionEnvironment','multi-gpu');    % set up the GPU environment for training

% load the network 
RF_UAVNet
% start the training process
trainednet = trainNetwork(imdsTrain,lgraph,options);

% measure the accuracy on the testing set.
YPred = classify(trainednet,imdsTest,'MiniBatchSize',512,'ExecutionEnvironment','gpu');
YTest = imdsTest.Labels;
accuracy = sum(YPred == YTest)/numel(YTest)
